// Generated by Wrangler on Mon Jun 10 2024 17:28:01 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

export interface Env {
	LINK_SHORTENER: KVNamespace;
	API_KEY: string;
	MAX_TTL: string;
	ROOT_REDIRECT: string;
	SLUG_LENGTH: string;
}
declare module "*.html" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.css" {
	const value: ArrayBuffer;
	export default value;
}