name = "link-shortener"
main = "src/index.ts"
compatibility_date = "2023-08-14"
node_compat = true
workers_dev = false

routes = [
	{ pattern = "demo.linkshortener.dev", custom_domain = true }
]

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
vars = { API_KEY = "testing-password", MAX_TTL = "315360000", ROOT_REDIRECT = "https://mackenly.com", SLUG_LENGTH = "6" }

# Allow HTML and CSS files to be imported from within TypeScript files.
rules = [
    { type = "Data", globs = ["**/*.html"], fallthrough = true },
    { type = "Data", globs = ["**/*.css"], fallthrough = true }
]

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
kv_namespaces = [
    { binding = "LINK_SHORTENER", id = "yourkey", preview_id = "yourkey" }
]
