name = "link-shortener-demo"
main = "src/index.ts"
compatibility_date = "2023-08-14"
node_compat = true

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
vars = { API_KEY = "#b6Ybk~@p!74%3@WCi", MAX_TTL = "61", ROOT_REDIRECT = "", SLUG_LENGTH = "6" }

# Allow HTML and CSS files to be imported from within TypeScript files.
rules = [
    { type = "Data", globs = ["**/*.html"], fallthrough = true },
    { type = "Data", globs = ["**/*.css"], fallthrough = true }
]

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
kv_namespaces = [
    { binding = "LINK_SHORTENER", id = "cd4c59e543e841d080f1c9fc017bb7dc", preview = "d1a4c7f10ee049a2a1b4516b9705f7c5" }
]
