name: Run Tests

on:
  push:
    paths:
      - 'link-shortener/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: ./link-shortener

    - name: Run tests
      run: npm test
      working-directory: ./link-shortener